version: '2'

services:
  bot:
    image: crystallang/crystal:0.22.0
    command: crystal examples/echo_bot.cr
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      VERIFY_TOKEN: "VERIFY_ME"
  ngrok:
    image: fnichol/ngrok
    command: "bot:80"
    volumes:
      - './ngrok.yml:/root/ngrok.yml'
    ports:
      - 4040:4040
